Exception:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/site-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/site-packages/pip/req/req_set.py", line 346, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/site-packages/pip/req/req_uninstall.py", line 103, in remove
    response = ask('Proceed (y/n)? ', ('y', 'n'))
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/site-packages/pip/utils/__init__.py", line 158, in ask
    response = input(message)
EOFError: EOF when reading a line
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: Tesla M40 24GB
major: 5 minor: 2 memoryClockRate (GHz) 1.112
pciBusID 0000:02:00.0
Total memory: 22.43GiB
Free memory: 22.32GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x6322de70
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 1 with properties: 
name: Tesla M40 24GB
major: 5 minor: 2 memoryClockRate (GHz) 1.112
pciBusID 0000:03:00.0
Total memory: 22.43GiB
Free memory: 22.32GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 1:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla M40 24GB, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla M40 24GB, pci bus id: 0000:03:00.0)
  0%|          | 0/10000 [00:00<?, ?it/s]I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 77337 get requests, put_count=29511 evicted_count=1000 eviction_rate=0.0338857 and unsatisfied allocation rate=0.632634
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:257] Raising pool_size_limit_ from 100 to 110
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 3575 get requests, put_count=6589 evicted_count=3000 eviction_rate=0.455304 and unsatisfied allocation rate=0
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 13405 get requests, put_count=26408 evicted_count=13000 eviction_rate=0.492275 and unsatisfied allocation rate=0.000820589
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 23231 get requests, put_count=46229 evicted_count=23000 eviction_rate=0.497523 and unsatisfied allocation rate=0.000688735
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 33038 get requests, put_count=66032 evicted_count=33000 eviction_rate=0.499758 and unsatisfied allocation rate=0.000605364
  0%|          | 1/10000 [00:08<24:12:39,  8.72s/it]I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 2005 get requests, put_count=2949 evicted_count=1000 eviction_rate=0.339098 and unsatisfied allocation rate=0.036409
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:257] Raising pool_size_limit_ from 193 to 212
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 11993 get requests, put_count=22012 evicted_count=10000 eviction_rate=0.454298 and unsatisfied allocation rate=0
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 21831 get requests, put_count=41849 evicted_count=20000 eviction_rate=0.477909 and unsatisfied allocation rate=4.58064e-05
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 31733 get requests, put_count=61750 evicted_count=30000 eviction_rate=0.48583 and unsatisfied allocation rate=6.30259e-05
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 41743 get requests, put_count=81759 evicted_count=40000 eviction_rate=0.489243 and unsatisfied allocation rate=7.18683e-05
  0%|          | 2/10000 [00:11<19:17:36,  6.95s/it]I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 152196 get requests, put_count=139116 evicted_count=50000 eviction_rate=0.359412 and unsatisfied allocation rate=0.41459
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:257] Raising pool_size_limit_ from 212 to 233
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 10965 get requests, put_count=19988 evicted_count=9000 eviction_rate=0.45027 and unsatisfied allocation rate=0
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 20729 get requests, put_count=39752 evicted_count=19000 eviction_rate=0.477963 and unsatisfied allocation rate=0
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 32723 get requests, put_count=61746 evicted_count=29000 eviction_rate=0.469666 and unsatisfied allocation rate=0
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 42591 get requests, put_count=81613 evicted_count=39000 eviction_rate=0.477865 and unsatisfied allocation rate=2.34791e-05
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 53813 get requests, put_count=102835 evicted_count=49000 eviction_rate=0.476491 and unsatisfied allocation rate=1.85829e-05
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 65320 get requests, put_count=124341 evicted_count=59000 eviction_rate=0.474502 and unsatisfied allocation rate=3.06185e-05
  0%|          | 3/10000 [00:15<16:35:43,  5.98s/it]Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/696/bidaf/basic/cli.py", line 111, in <module>
    tf.app.run()
  File "/home/usaxena/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/usaxena/work/s18/696/bidaf/basic/cli.py", line 108, in main
    m(config)
  File "/home/usaxena/work/s18/696/bidaf/basic/main.py", line 23, in main
    _train(config)
  File "/home/usaxena/work/s18/696/bidaf/basic/main.py", line 99, in _train
    loss, summary, train_op = trainer.step(sess, batches, get_summary=get_summary)
  File "/home/usaxena/work/s18/696/bidaf/basic/trainer.py", line 65, in step
    feed_dict.update(model.get_feed_dict(ds, True))
  File "/home/usaxena/work/s18/696/bidaf/basic/model.py", line 316, in get_feed_dict
    y[i, j, k] = True
IndexError: index 341 is out of bounds for axis 2 with size 155
